### ISSUE TITLE
怎么报错？

### ISSUE THREAD

**Issue by lianfulei** [hk029/LagouSpider#2]
2016-09-01 10:48:39 [scrapy] ERROR: Spider error processing <POST http://www.lagou.com/jobs/positionAjax.json> (referer: None)
Traceback (most recent call last):
  File "/usr/local/python2.7/lib/python2.7/site-packages/scrapy/utils/defer.py", line 102, in iter_errback
    yield next(it)
  File "/usr/local/python2.7/lib/python2.7/site-packages/scrapy/spidermiddlewares/offsite.py", line 29, in process_spider_output
    for x in result:
  File "/usr/local/python2.7/lib/python2.7/site-packages/scrapy/spidermiddlewares/referer.py", line 22, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "/usr/local/python2.7/lib/python2.7/site-packages/scrapy/spidermiddlewares/urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "/usr/local/python2.7/lib/python2.7/site-packages/scrapy/spidermiddlewares/depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "/root/scrapy/lagouSpider-master/lagou/spiders/LagouPositon.py", line 50, in parse
    item['companyName'] = each['companyName']
KeyError: 'companyName'
2016-09-01 10:48:39 [scrapy] INFO: Closing spider (finished)

**Comment by lianfulei** [comment]
我把这个去掉了可以了item['companyName'] = each['companyName']
